
### Signuup and create a new user in database
POST http://localhost:3000/auth/signup
content-type: application/json

{
    "email": "big@bone1.com",
    "password": "123abc"
}

### sign in user
POST http://localhost:3000/auth/signin
content-type: application/json

{
    "email": "eric@cartman.com",
    "password": "123abc"
}

### get currently logged in user (get me)

GET http://localhost:3000/auth/whoami

### Sign out logged in user
POST http://localhost:3000/auth/signout


### Find particular user with give id

GET http://localhost:3000/auth/2

### list all users with given email

GET http://localhost:3000/auth?email=johnny@bravo.com

### delete user with given ID

DELETE http://localhost:3000/auth/1

### update user with given id

PATCH http://localhost:3000/auth/2
content-type: application/json

{
    "email": "abc@abc.com"
}

# ### set color testing purposes
# GET http://localhost:3000/auth/colors/red

# ### get color
# GET http://localhost:3000/auth/colors
